services:
  postgres:
    image: 'postgres:13.16'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  minio:
    image: 'minio/minio'
    ports:
      - "9001:9000"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678


  redis:
    image: 'redis:latest'
    ports:
      - '6379'
