services:
  postgres:
    image: 'postgres:13.16'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456


  redis:
    image: 'redis:latest'
    ports:
      - '6379'
